name: Super Simple APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - run: |
        mkdir www
        echo '<html><head><title>Brain Games</title></head><body><h1>Brain Games Hub</h1><p>Ready to play!</p></body></html>' > www/index.html
    - run: npm install -g @capacitor/cli @capacitor/core @capacitor/android
    - run: |
        echo 'import type { CapacitorConfig } from "@capacitor/cli";
        const config: CapacitorConfig = {
          appId: "com.braingames.hub",
          appName: "Brain Games Hub",
          webDir: "www"
        };
        export default config;' > capacitor.config.ts
    - run: npx cap add android
    - run: cd android && chmod +x gradlew && ./gradlew assembleDebug
    - uses: actions/upload-artifact@v3
      with:
        name: apk-file
        path: android/app/build/outputs/apk/debug/app-debug.apk
